sim_logger:
  animation_enabled: false

map:
  # path from pkg share dir
  yaml_path: "env/final_ver2/occupancy_grid_map.yaml"

waypoints:
  # path from pkg share dir
  # csv_path: "maps/occupancy_grid_map_waypoints.csv"
  csv_path: ""

obstacles:
  # path from pkg share dir
  csv_path: "" # If empty, the obstacles information will be subscribed from the topic
  # csv_path: "maps/occupancy_grid_map_obstacles.csv"
  radius: 1.25

reference_path:
  update_by_topic: false # When true, 'circle' must be false
  # path from pkg share dir
  csv_path: ""
  csv_path: "env/final_ver2/traj_mincurv.csv"
  resolution: 0.6
  smoothing_distance: 2
  max_width: 6.0
  circular: true
  use_path_constraints_topic: false
  use_border_cells_topic: false
  # use_path_constraints_topic: true
  # use_border_cells_topic: true

bicycle_model:
  length: 1.087
  # width: 1.45   # real machine width
  width: 2.30   # +safety margin

mpc:
  N: 20
  Q: [5.0, 100.0, 0.08]  # [v, delta, t]
  # Q: [3.0, 100.0, 5.0]  # [v, delta, t]
  # Q: [5.0, 90.0, 5.0]  # [v, delta, t]
  # Q: [10.0, 80.0, 5.0]  # [v, delta, t]
  R: [1.0, 500.0]      # [v, delta]
  QN: [5.0, 500.0, 0.08]  # [v, delta, t]
  v_max: 30.0 # km/h
  a_min: -3.2 # m/s^2
  a_max: 3.2 # m/s^2
  ay_max: 7.5 # m/s^2, maximum lateral acceleration in curves
  delta_max_deg: 35.0 # degrees
  control_rate: 40.0 # Hz
  steering_tire_angle_gain_var: 1.639


