ref_vel_configulator:
  s1:
    ref_vel: 30.0
    wp_id: 1
  s2:
    ref_vel: 30.0
    wp_id: 20
  s3:
    ref_vel: 30.0
    wp_id: 55
  s4:
    ref_vel: 30.0
    wp_id: 131
  s5:
    ref_vel: 30.0
    wp_id: 156
  s6:
    ref_vel: 30.0
    wp_id: 320
