sect_1:
  wp_id: 1
  ref_vel: 5.0

sect_2:
  wp_id: 20
  ref_vel: 30.0

sect_3:
  wp_id: 55
  ref_vel: 25.0

sect_4:
  wp_id: 131
  ref_vel: 30.0

sect_5:
  wp_id: 156
  ref_vel: 25.0

sect_6:
  wp_id: 320
  ref_vel: 20.0

