#!/usr/bin/env python3

import sys
import threading

# ROS 2
import rclpy
from rclpy.signals import SignalHandlerOptions
from rclpy.executors import MultiThreadedExecutor

# Project
from multi_purpose_mpc_ros.ref_path_visualizer import ReferencePathVisualizer
from multi_purpose_mpc_ros.common import parse_args_without_ros


def main(argv = sys.argv) -> None:

    args = parse_args_without_ros(argv)
    rclpy.init(args=argv, signal_handler_options=SignalHandlerOptions.NO)
    executor = MultiThreadedExecutor(num_threads=2)

    node = ReferencePathVisualizer(args.config_path)
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main(sys.argv)