#!/usr/bin/env python3

import sys

# ROS 2
import rclpy
from rclpy.signals import SignalHandlerOptions

# Project
from multi_purpose_mpc_ros.velocity_heat_odom_visualizer import VelocityHeatOdomVisualizer
from multi_purpose_mpc_ros.common import parse_args_without_ros


def main(argv = sys.argv) -> None:

    rclpy.init(args=argv, signal_handler_options=SignalHandlerOptions.NO)

    node = VelocityHeatOdomVisualizer()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main(sys.argv)