#!/usr/bin/env python3

import sys
import threading

# ROS 2
import rclpy
from rclpy.executors import MultiThreadedExecutor

# Project
from multi_purpose_mpc_ros.mpc_controller import MPCController
from multi_purpose_mpc_ros.common import parse_args_without_ros


def main(argv = sys.argv) -> None:

    args = parse_args_without_ros(argv)
    rclpy.init(args=argv)
    executor = MultiThreadedExecutor()

    try:
        node = MPCController(args.config_path)
        executor.add_node(node)
        executor_thread = threading.Thread(target=executor.spin)
        executor_thread.start()
        node.run()

    except KeyboardInterrupt:
        node.get_logger().info("Shutdown requested")
    finally:
        node.destroy_node()


if __name__ == "__main__":
    main(sys.argv)